### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by igakigongo** [shjang7/bing_search_command#1]
Thanks for the presentation.

Although I got in late, I just got a small glimpse of it.

Kindly research about [jsoup](https://jsoup.org/), when you talked about web scrapping, I then recalled that I have come across it before. It might be of some help in that direction.

Regards,
Edward

**Comment by shjang7** [comment]
@igakigongo It is a nice suggestion, 
If I build an app with JS, I will try it with that approach.
Thanks for your ideas.
